name: Deploy API to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/deploy.yml'

env:
  PROJECT_ID: rowadi
  REGION: us-central1
  ARTIFACT_REPO: api-repo
  APP_NAME: ons-api

jobs:
  deploy-api:
    name: Build and Deploy API Image
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.APP_NAME }}:latest

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.APP_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.APP_NAME }}:latest

      - name: Show Output
        run: echo "Successfully deployed to ${{ steps.deploy.outputs.url }}"